{
    "director_id": "4be01dcc-3c42-4908-4387-dcfdc6b9cc20",
    "installation_id": "eea705fb-de43-427a-6381-5ccf63358a78",
    "current_vm_cid": "i-09f86813f319c43d8",
    "current_stemcell_id": "a011bed4-a3d4-4725-6574-12c902ec33de",
    "current_disk_id": "26d41a31-c2e2-4bd5-62d7-d60cc0d87f08",
    "current_release_ids": [
        "eea91584-5b57-44ba-7704-fe010bc72cb4",
        "0648eca3-051e-4d21-51d9-589b3855bc18",
        "e6789ec9-3bd3-436d-5de0-02c29bdd9643",
        "7ea65da7-f795-4f0a-50d9-1b84fc581ab5",
        "6cb56211-07a8-4d45-4c63-44067ccb2634",
        "e80a8eb4-f95c-41a3-4b2e-837fbe3b32e6"
    ],
    "current_manifest_sha": "6a5a6ed59ec016d9f791d5a0c8b25a1630018eda5dfced7d3b7b56687a227f8647a31a0c3b34a0cb1c46c486d7af539edf671971652dc745b447525e3758edc1",
    "disks": [
        {
            "id": "26d41a31-c2e2-4bd5-62d7-d60cc0d87f08",
            "cid": "vol-022531957e0b961d8",
            "size": 32768,
            "cloud_properties": {
                "type": "gp2"
            }
        }
    ],
    "stemcells": [
        {
            "id": "a011bed4-a3d4-4725-6574-12c902ec33de",
            "name": "bosh-aws-xen-hvm-ubuntu-bionic-go_agent",
            "version": "1.41",
            "api_version": 3,
            "cid": "ami-0e2c27494dbfe34c6 light"
        }
    ],
    "releases": [
        {
            "id": "eea91584-5b57-44ba-7704-fe010bc72cb4",
            "name": "bosh",
            "version": "271.17.0"
        },
        {
            "id": "0648eca3-051e-4d21-51d9-589b3855bc18",
            "name": "bpm",
            "version": "1.1.15"
        },
        {
            "id": "e6789ec9-3bd3-436d-5de0-02c29bdd9643",
            "name": "uaa",
            "version": "75.12.0"
        },
        {
            "id": "7ea65da7-f795-4f0a-50d9-1b84fc581ab5",
            "name": "credhub",
            "version": "2.11.0"
        },
        {
            "id": "6cb56211-07a8-4d45-4c63-44067ccb2634",
            "name": "bosh-aws-cpi",
            "version": "91"
        },
        {
            "id": "e80a8eb4-f95c-41a3-4b2e-837fbe3b32e6",
            "name": "os-conf",
            "version": "22.1.2"
        }
    ]
}