pipeline:
  name: bosh-mgmt-platform-pipeline
  git:
    owner: starkandwayne
    repo:  demo-bosh-deployments
    branch: master
    private_key: (( vault "concourse/demo/bosh/github:private_key" ))

  slack:
    channel: '#concourse'
    webhook: (( vault "concourse/demo/bosh/slack:webhook" ))

  vault:
    url:    https://10.4.1.7
    verify: no


  boshes:
    uswest2demo:
    dev:
      alias:    dev
      url:      https://10.4.16.4:25555
      ca_cert:  (( vault "secret/dev/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/dev/bosh/users/admin:password" ))

    
  layouts:
    default: |+
      auto *uswest2demo
      uswest2demo -> dev

  groups:
    default:
    - uswest2demo
    - dev