################################################################################
# Availability Zones
################################################################################
azs:
  - name: z1
    cloud_properties: { availability_zone: us-west-2a }
  - name: z2
    cloud_properties: { availability_zone: us-west-2b }
  - name: z3
    cloud_properties: { availability_zone: us-west-2c }

################################################################################
# VM Types
################################################################################
vm_types:
  - {name: api,              cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: as-api,           cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-broker,        cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-collector,     cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-engine,        cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-operator,      cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-scaler,        cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-scheduler,     cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: bbs,              cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: blobstore,        cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: bosh,             cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  24576, type: gp3, encrypted: true}}}
  - {name: cc-worker,        cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: compilation,      cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  65536, type: gp3, encrypted: true}}}
  - {name: concourse-worker, cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  65536, type: gp3, encrypted: true}}}
  - {name: credhub,          cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: default,          cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: diego-cell,       cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size: 262144, type: gp3, encrypted: true}}}
  - {name: diego-api,        cloud_properties: {instance_type: t3.nano, ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: doppler,          cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: errand,           cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: haproxy,          cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: large,            cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: log-api,          cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: medium,           cloud_properties: {instance_type: t3.micro,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: minimal,          cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: nats,             cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: postgres,         cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: router,           cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: scheduler,        cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: small,            cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: small-cf,         cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: small-highmem,    cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  24576, type: gp3, encrypted: true}}}
  - {name: syslogger,        cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: tcp-router,       cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: thunder-dome,     cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  81920, type: gp3, encrypted: true}}}
  - {name: uaa,              cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  # Blacksmith
  - {name: blacksmith,                 cloud_properties: {instance_type: t3.medium,   ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-redis-small,     cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-redis-medium,    cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-redis-large,     cloud_properties: {instance_type: t3.large, ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-rabbitmq-medium, cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-rabbitmq-large,  cloud_properties: {instance_type: t3.medium, ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}

################################################################################
# Disk Types
################################################################################
disk_types:
  - {name: "default",    disk_size:   2048, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "consul",     disk_size:   2048, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "concourse",  disk_size:  10240, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "postgres",   disk_size:   4096, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "blobstore",  disk_size:   4096, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "vault",      disk_size:   1024, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "bosh",       disk_size:  65536, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "bosh-large", disk_size: 131072, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "shield",     disk_size:   2048, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "prometheus", disk_size:  51200, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "rabbitmq",   disk_size:   4096, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "5GB",        disk_size:   5120, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "10GB",       disk_size:  10240, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "100GB",      disk_size: 100240, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "minio",      disk_size:  10240, cloud_properties: {type: gp3, encrypted: true}}

################################################################################
# Compilation
################################################################################
compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: default

################################################################################
# VM Extensions
################################################################################
vm_extensions:
  # - {"name": "cf-elb"}             # CW: Appear to be deprecated
  # - {"name": "ssh-elb"}            # CW: Appear to be deprecated
  # - {"name": "cf-load-balanced"}   # CW: Appear to be deprecated
  - name: 100GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 102400
        type: gp3
  - name: 50GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 51200
        type: gp3
  - name: cf-router-network-properties
    cloud_properties:
    #  lb_target_groups:
    #    - codex-cf-alb-tg
      elbs:
        - snw-dev-cf-elb
  - name: cf-tcp-router-network-properties
    cloud_properties:
      elbs:
        - dev-cf-tcp-lb

  - name: diego-ssh-proxy-network-properties

################################################################################
# Networks
################################################################################
networks:
  - name: default
    type: manual
    subnets:
      - range: 10.4.16.0/24
        gateway: 10.4.16.1
        azs: ["z1"]
        static: [10.4.16.6-10.4.16.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0ea631cc3ad19e04f} #snw-dev-infra-0
        reserved: [10.4.16.0-10.4.16.5, 10.4.16.245-10.4.16.254]
      - range: 10.4.17.0/24
        gateway: 10.4.17.1
        azs: ["z2"]
        static: [10.4.17.6-10.4.17.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-09a05edb82702379b} #snw-dev-infra-1
        reserved: [10.4.17.0-10.4.17.5]
      - range: 10.4.18.0/24
        gateway: 10.4.18.1
        azs: ["z3"]
        static: [10.4.18.6-10.4.18.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0dd034854c197dc41} #snw-dev-infra-2
        reserved: [10.4.18.0-10.4.18.5]

  - name: compilation
    type: manual
    subnets:
      - range: 10.4.16.0/24
        gateway: 10.4.16.1
        azs: ["z1"]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0ea631cc3ad19e04f} #snw-dev-infra-0
        reserved: [10.4.16.0-10.4.16.244]

  - name: cf-db
    type: manual
    subnets:
      - range: 10.4.29.0/28
        gateway: 10.4.29.1
        azs: ["z1"]
        static: [10.4.29.4-10.4.29.14]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-03720ac266d128f29} #snw-dev-cf-db-0
        reserved: [10.4.29.0-10.4.29.3]
      - range: 10.4.29.16/28
        gateway: 10.4.29.17
        azs: ["z2"]
        static: [10.4.29.20-10.4.29.30]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-015b5284fb46c07e6} #snw-dev-cf-db-1
        reserved: [10.4.29.16-10.4.29.19]
      - range: 10.4.29.32/28
        gateway: 10.4.29.33
        azs: ["z3"]
        static: [10.4.29.36-10.4.29.46]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-05dcf16f08f546160} #snw-dev-cf-db-2
        reserved: [10.4.29.32-10.4.29.35]


  - name: cf-edge
    type: manual
    subnets:
      - range: 10.4.62.0/25
        gateway: 10.4.62.1
        azs: ["z1"]
        static: [10.4.62.4-10.4.62.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0bdaf27eb328f7e4d} #snw-dev-cf-edge-internal-0
        reserved:
          - 10.4.62.0-10.4.62.3
          - 10.4.62.64 - 10.4.62.126 # leave this to 'ocfp-dev' director
      - range: 10.4.62.128/25
        gateway: 10.4.62.129
        azs: ["z2"]
        static: [10.4.62.132-10.4.17.144]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-048560ab22b7c345f} #snw-dev-cf-edge-internal-1
        reserved:
          - 10.4.62.128-10.4.62.131
          - 10.4.62.192 - 10.4.62.254 # leave this to 'ocfp-dev' director

  # - name: cf-edge
  #   type: manual
  #   subnets:
  #     - range: 10.4.19.0/25
  #       gateway: 10.4.19.1
  #       azs: ["z1"]
  #       static: [10.4.19.4-10.4.19.16]
  #       dns: [1.1.1.1, 8.8.4.4]
  #       cloud_properties: {subnet: subnet-0c5dcce6ff1ff8ffc} #snw-dev-cf-edge-0
  #       reserved: [10.4.19.0-10.4.19.3, 10.4.19.17]
  #     - range: 10.4.19.128/25
  #       gateway: 10.4.19.129
  #       azs: ["z2"]
  #       static: [10.4.19.132-10.4.17.144]
  #       dns: [1.1.1.1, 8.8.4.4]
  #       cloud_properties: {subnet: subnet-0c0f58272fa0f3b17} #snw-dev-cf-edge-1
  #       reserved: [10.4.19.128-10.4.19.131]

  - name: cf-core
    type: manual
    subnets:
      - range: 10.4.20.0/24
        gateway: 10.4.20.1
        azs: ["z1"]
        static: [10.4.20.6-10.4.20.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0a00811172726ce3b} #snw-dev-cf-core-0
        reserved:
          - 10.4.20.0-10.4.20.5
          - 10.4.20.128 - 10.4.20.254 # leave this to 'ocfp-dev' director
      - range: 10.4.21.0/24
        gateway: 10.4.21.1
        azs: ["z2"]
        static: [10.4.21.6-10.4.21.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-03e4614c67b6af3d5} #snw-dev-cf-core-1
        reserved:
          - 10.4.21.0-10.4.21.5
          - 10.4.21.128 - 10.4.21.254 # leave this to 'ocfp-dev' director
      - range: 10.4.22.0/24
        gateway: 10.4.22.1
        azs: ["z3"]
        static: [10.4.22.6-10.4.22.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-04ecdc31ba8c3d685} #snw-dev-cf-core-2
        reserved:
          - 10.4.22.0-10.4.22.5
          - 10.4.22.128 - 10.4.22.254 # leave this to 'ocfp-dev' director

  - name: cf-runtime
    type: manual
    subnets:
      - range: 10.4.23.0/24
        gateway: 10.4.23.1
        azs: ["z1"]
        static: [10.4.23.6-10.4.23.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-08f6940f71c779a15} #snw-dev-cf-runtime-0
        reserved:
          - 10.4.23.0-10.4.23.5
          - 10.4.23.128 - 10.4.23.254 # leave this to 'ocfp-dev' director
      - range: 10.4.24.0/24
        gateway: 10.4.24.1
        azs: ["z2"]
        static: [10.4.24.6-10.4.24.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0964231d662ce7e9b} #snw-dev-cf-runtime-1
        reserved:
          - 10.4.24.0-10.4.24.5
          - 10.4.24.128 - 10.4.24.254 # leave this to 'ocfp-dev' director
      - range: 10.4.25.0/24
        gateway: 10.4.25.1
        azs: ["z3"]
        static: [10.4.25.6-10.4.25.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0e513e543403b53ac} #snw-dev-cf-runtime-2
        reserved:
          - 10.4.25.0-10.4.25.5
          - 10.4.25.128 - 10.4.25.254 # leave this to 'ocfp-dev' director

  - name: concourse-ips
    type: manual
    subnets:
      - range: 10.4.68.0/24
      gateway: 10.4.68.1
      azs: ["z1"]
      static: [10.4.68.6-10.4.68.16]
      dns: [1.1.1.1, 8.8.4.4]
      cloud_properties: {subnet: subnet-004e38051f36dae09} #snw-dev-cf-edge-internal-0
      reserved: [10.4.68.0-10.4.68.5]

  - name: blacksmith
    type: manual
    subnets:
      - range: 10.4.26.0/24
        gateway: 10.4.26.1
        azs: ["z1"] # us-west-2a
        static: [10.4.26.6-10.4.26.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-062565d28649eeb00} #snw-dev-cf-svc-0
        reserved: [10.4.26.0-10.4.26.5, 10.4.26.245-10.4.26.254]
      - range: 10.4.27.0/24
        gateway: 10.4.27.1
        azs: ["z2"] # us-west-2b
        static: [10.4.27.6-10.4.27.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-0d10710c119782f5f} #snw-dev-cf-svc-1
        reserved: [10.4.27.0-10.4.27.5]
      - range: 10.4.28.0/24
        gateway: 10.4.28.1
        azs: ["z3"] # us-west-2c
        static: [10.4.28.6-10.4.28.16]
        dns: [1.1.1.1, 8.8.4.4]
        cloud_properties: {subnet: subnet-06fb1168c8fba4e45} #snw-dev-cf-svc-2
        reserved: [10.4.28.0-10.4.28.5]
