azs:
- name: z1
  cloud_properties: {availability_zone: us-west-2a}

################################################################################
# vm_types
################################################################################
vm_types:
  - {name: api,              cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: as-api,           cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-broker,        cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-collector,     cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-engine,        cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-operator,      cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-scaler,        cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: as-scheduler,     cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: bbs,              cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: blobstore,        cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: bosh,             cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  24576, type: gp3, encrypted: true}}}
  - {name: cc-worker,        cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: compilation,      cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  65536, type: gp3, encrypted: true}}}
  - {name: concourse-worker, cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  65536, type: gp3, encrypted: true}}}
  - {name: credhub,          cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: default,          cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: diego-cell,       cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size: 262144, type: gp3, encrypted: true}}}
  - {name: diego-api,        cloud_properties: {instance_type: t3.nano, ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: doppler,          cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: errand,           cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: haproxy,          cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: large,            cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: log-api,          cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: medium,           cloud_properties: {instance_type: t3.micro,  ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  - {name: minimal,          cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: nats,             cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: postgres,         cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  32768, type: gp3, encrypted: true}}}
  - {name: router,           cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: scheduler,        cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: small,            cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: small-cf,         cloud_properties: {instance_type: t3.nano,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: small-highmem,    cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:  24576, type: gp3, encrypted: true}}}
  - {name: syslogger,        cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: tcp-router,       cloud_properties: {instance_type: t3.nano,   ephemeral_disk: {size:   8192, type: gp3, encrypted: true}}}
  - {name: thunder-dome,     cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  81920, type: gp3, encrypted: true}}}
  - {name: uaa,              cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  16384, type: gp3, encrypted: true}}}
  # Blacksmith
  - {name: blacksmith,                 cloud_properties: {instance_type: t3.medium,   ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-redis-small,     cloud_properties: {instance_type: t3.small,   ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-redis-medium,    cloud_properties: {instance_type: t3.medium,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-redis-large,     cloud_properties: {instance_type: t3.large, ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-rabbitmq-medium, cloud_properties: {instance_type: t3.small,  ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}
  - {name: blacksmith-rabbitmq-large,  cloud_properties: {instance_type: t3.medium, ephemeral_disk: {size:  10240, type: gp3, encrypted: true}}}

################################################################################
# Disk Types
################################################################################
disk_types:
  - {name: "default",    disk_size:   2048, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "consul",     disk_size:   2048, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "concourse",  disk_size:  10240, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "postgres",   disk_size:   4096, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "blobstore",  disk_size:   4096, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "vault",      disk_size:   1024, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "bosh",       disk_size:  65536, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "bosh-large", disk_size: 131072, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "shield",     disk_size:   2048, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "prometheus", disk_size:  51200, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "rabbitmq",   disk_size:   4096, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "5GB",        disk_size:   5120, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "10GB",       disk_size:  10240, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "100GB",      disk_size: 100240, cloud_properties: {type: gp3, encrypted: true}}
  - {name: "minio",      disk_size:  10240, cloud_properties: {type: gp3, encrypted: true}}

################################################################################
# Compilation
################################################################################
compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: default

################################################################################
# VM Extensions
################################################################################
vm_extensions:
#   - {"name": "cf-elb"}             # CW: Appear to be deprecated
#   - {"name": "ssh-elb"}            # CW: Appear to be deprecated
#   - {"name": "cf-load-balanced"}   # CW: Appear to be deprecated
  - name: 100GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 102400
        type: gp3
  - name: 50GB_ephemeral_disk
    cloud_properties:
      ephemeral_disk:
        size: 51200
        type: gp3  
  - name: cf-router-network-properties
    cloud_properties:
#      lb_target_groups:
#        - codex-cf-alb-tg
      elbs: 
        - snw-dev-cf-elb
  - name: cf-tcp-router-network-properties
    cloud_properties:
      elbs:
        - dev-cf-tcp-lb

  - name: diego-ssh-proxy-network-properties

networks:
- name: default
  type: manual
  subnets:                                                 ### ADDED !!!
  - range: 10.4.69.0/24                                    ### ADDED !!!
    gateway: 10.4.69.1                                     ### ADDED !!!
    azs: ["z1"]                                            ### ADDED !!!
    static: [10.4.69.6-10.4.69.16]                         ### ADDED !!!
    dns: [1.1.1.1, 8.8.4.4]                                ### ADDED !!!
    cloud_properties: {subnet: subnet-0dcf8272f03fead6d} # subnet-064b78e587e3b8bf5}   ### ADDED !!!  Subnet snw-dev-infra-0
    reserved: [10.4.69.0-10.4.69.5]                        ### ADDED !!!  Reserved by AWS
    #- name: concourse-ips                                                                     
    # type: manual                                                                      
    #subnets:                                                                          
    # - range: 10.4.68.0/24                                                             
    #gateway: 10.4.68.1                                                              
    #azs: ["z1"]                                                                     
    #static: [10.4.68.6-10.4.68.16]                                                  
    #dns: [1.1.1.1, 8.8.4.4]                                                         
    #cloud_properties: {subnet: subnet-004e38051f36dae09} #snw-dev-cf-edge-internal-0
    #reserved: [10.4.68.0-10.4.68.5] 
- name: cf-edge                                                                     
  type: manual                                                                      
  subnets:                                                                          
  - range: 10.4.35.0/25                                                             
    gateway: 10.4.35.1                                                              
    azs: ["z1"]                                                                     
    static: [10.4.35.6-10.4.35.16]                                                  
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-07d4502687a40fe9c}  #cf staging edge 1
    reserved: [10.4.35.0-10.4.35.127]  
- name: cf-runtime                                                                     
  type: manual                                                                      
  subnets:                                                                          
  - range: 10.4.65.0/24                                                             
    gateway: 10.4.65.1                                                              
    azs: ["z1"]                                                                     
    static: [10.4.65.6-10.4.65.16]                                                  
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-017e62bca32e491ea} #snw-dev-cf-edge-internal-0
    reserved: [10.4.65.0-10.4.65.5]
- name: cf-core                                                                  
  type: manual                                                                      
  subnets:                                                                          
  - range: 10.4.66.0/24                                                             
    gateway: 10.4.66.1                                                              
    azs: ["z1"]                                                                     
    static: [10.4.66.6-10.4.66.16]                                                  
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-06001ccd9bca8ac63} #snw-dev-cf-edge-internal-0
    reserved: [10.4.66.0-10.4.66.5]   
