azs:
- name: z1
  cloud_properties: {availability_zone: us-west-2a}
- name: z2
  cloud_properties: {availability_zone: us-west-2b}
- name: z3
  cloud_properties: {availability_zone: us-west-2c}

vm_types:
- name: default
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk: {size: 3000, type: gp2}
- name: large
  cloud_properties:
    instance_type: t3.large
    ephemeral_disk: {size: 30000, type: gp2}
- name: bosh                                               ### ADDED !!! 
  cloud_properties:                                        ### ADDED !!!
    instance_type: t3.medium                               ### ADDED !!!
    ephemeral_disk: {size: 25000, type: gp2}               ### ADDED !!!
- name: concourse
  cloud_properties:
    instance_type: t3.large
    ephemeral_disk: {size: 10240, type: gp3}
- name: concourse-worker                                                                   
  cloud_properties:                                                                 
    instance_type: t3.medium                                                        
    ephemeral_disk: {size: 65536, type: gp3}

disk_types:
- name: default
  disk_size: 3000
  cloud_properties: {type: gp2}
- name: large
  disk_size: 50_000
  cloud_properties: {type: gp2}
- name: bosh                                               ### ADDED !!!
  disk_size: 50_000                                        ### ADDED !!!
  cloud_properties: {type: gp2}                            ### ADDED !!!
- name: concourse
  disk_size: 10_240
  cloud_properties: {type: gp3}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.4.1.0/24
    gateway: 10.4.1.1
    azs: ["z1"]
    static: [10.4.1.6-10.4.1.16]
    dns: [1.1.1.1, 8.8.4.4]
    cloud_properties: {subnet: subnet-0f56fcba8b1ba95b3}
    reserved: [10.4.1.0-10.4.1.5]
  - range: 10.4.2.0/24
    gateway: 10.4.2.1
    azs: ["z2"]
    static: [10.4.2.6-10.4.2.16]
    dns: [1.1.1.1, 8.8.4.4]
    cloud_properties: {subnet: subnet-04066d0a30fd1c020}
    reserved: [10.4.2.0-10.4.2.5]
  - range: 10.4.3.0/24
    gateway: 10.4.3.1
    azs: ["z3"]
    static: [10.4.3.6-10.4.3.16]
    dns: [1.1.1.1, 8.8.4.4]
    cloud_properties: {subnet: subnet-0f2b10a0d103f3c83}
    reserved: [10.4.3.0-10.4.3.5]
- name: concourse                                                                     
  type: manual                                                                      
  subnets:                                                                          
  - range: 10.4.1.0/24                                                              
    gateway: 10.4.1.1                                                               
    azs: ["z1"]                                                                     
    static: [10.4.1.100-10.4.1.106]                                                    
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-0f56fcba8b1ba95b3}                            
    reserved: [10.4.1.0-10.4.1.99]
  - range: 10.4.2.0/24                                                           
    gateway: 10.4.2.1                                                            
    azs: ["z2"]                                                                     
    static: [10.4.2.100-10.4.2.106]                                                    
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-04066d0a30fd1c020}                            
    reserved: [10.4.2.0-10.4.2.99]                                                   
  - range: 10.4.3.0/24                                                              
    gateway: 10.4.3.1                                                               
    azs: ["z3"]                                                                     
    static: [10.4.3.100-10.4.3.106]                                                    
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-0f2b10a0d103f3c83}                            
    reserved: [10.4.3.0-10.4.3.99]

- name: concourse-full                                                                    
  type: manual                                                                      
  subnets:                                                                          
  - range: 10.4.1.0/24                                                              
    gateway: 10.4.1.1                                                               
    azs: ["z1"]                                                                     
    static: [10.4.1.150-10.4.1.156]                                                  
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-0f56fcba8b1ba95b3}                            
    reserved: [10.4.1.0-10.4.1.99]                                                  
  - range: 10.4.2.0/24                                                              
    gateway: 10.4.2.1                                                               
    azs: ["z2"]                                                                     
    static: [10.4.2.150-10.4.2.156]                                                  
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-04066d0a30fd1c020}                            
    reserved: [10.4.2.0-10.4.2.99]                                                   
  - range: 10.4.3.0/24                                                              
    gateway: 10.4.3.1                                                               
    azs: ["z3"]                                                                     
    static: [10.4.3.150-10.4.3.156]                                                  
    dns: [1.1.1.1, 8.8.4.4]                                                         
    cloud_properties: {subnet: subnet-0f2b10a0d103f3c83}                            
    reserved: [10.4.3.0-10.4.3.99] 
    
- name: dev                                                ### ADDED !!!
  type: manual                                             ### ADDED !!!
  subnets:                                                 ### ADDED !!!
  - range: 10.4.16.0/24                                    ### ADDED !!!
    gateway: 10.4.16.1                                     ### ADDED !!!
    azs: ["z1"]                                            ### ADDED !!!
    static: [10.4.16.4-10.4.16.16]                         ### ADDED !!!
    dns: [1.1.1.1, 8.8.4.4]                                ### ADDED !!!
    cloud_properties: {subnet: subnet-0ea631cc3ad19e04f}   ### ADDED !!!  Subnet snw-dev-infra-0
    reserved: [10.4.16.0-10.4.16.3]                        ### ADDED !!!  Reserved by AWS
  - range: 10.4.17.0/24                                    ### ADDED !!!
    gateway: 10.4.17.1                                     ### ADDED !!!
    azs: ["z2"]                                            ### ADDED !!!
    static: [10.4.17.4-10.4.17.16]                         ### ADDED !!!
    dns: [1.1.1.1, 8.8.4.4]                                ### ADDED !!!
    cloud_properties: {subnet: subnet-09a05edb82702379b}   ### ADDED !!!  Subnet snw-dev-infra-0
    reserved: [10.4.17.0-10.4.17.3]                        ### ADDED !!!  Reserved by AWS
  - range: 10.4.18.0/24                                    ### ADDED !!!
    gateway: 10.4.18.1                                     ### ADDED !!!
    azs: ["z3"]                                            ### ADDED !!!
    static: [10.4.18.4-10.4.18.16]                         ### ADDED !!!
    dns: [1.1.1.1, 8.8.4.4]                                ### ADDED !!!
    cloud_properties: {subnet: subnet-0dd034854c197dc41}   ### ADDED !!!  Subnet snw-dev-infra-0
    reserved: [10.4.18.0-10.4.18.3]                        ### ADDED !!!  Reserved by AWS
